# Generated by Django 4.1.2 on 2022-10-27 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdrawal', 'WITHDRAWAL'), ('transfer', 'TRANSFER')], max_length=10)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
