# Generated by Django 4.1.2 on 2022-10-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
