# Generated by Django 4.1.2 on 2022-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_transaction_record_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='source',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_record',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
