# Generated by Django 4.1.2 on 2022-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountrecord_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='account_type',
            field=models.CharField(choices=[('savings', 'SAVINGS'), ('current', 'CURRENT'), ('super_saving', 'SUPER_SAVING')], default='current', max_length=15),
        ),
        migrations.AlterField(
            model_name='transactionrecord',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdrawal', 'WITHDRAWAL'), ('transfer', 'TRANSFER'), ('interest', 'INTEREST')], max_length=10),
        ),
    ]
