# Generated by Django 4.1.2 on 2022-10-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_transaction_record_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_out_transactions', to='account.account_record'),
        ),
        migrations.AlterField(
            model_name='transaction_record',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_in_transactions', to='account.account_record'),
        ),
    ]
