# Generated by Django 4.1.2 on 2022-10-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_transaction_record_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='audit_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.IntegerField(default=0)),
                ('new_balance', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('account_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.account_record')),
            ],
        ),
    ]
